# Generated by Django 5.0 on 2023-12-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_teacher_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="city",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="student",
            name="country",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="student",
            name="image",
            field=models.ImageField(blank=True, upload_to="profile_pics/"),
        ),
        migrations.AddField(
            model_name="student",
            name="phone_number",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
